#!/bin/bash

# set -x

help() {
cat <<HSD
`basename $0` initialises the infrastucture for the aws auto-scaling demo.

The command line arguments are as follows:

    --action=[setup|teardown]   What to do [default: "setup"]

    --ami=ami           The AMI to use [default: ami-3bc7c54f]
    --azs=az1,az2       Availability zones [default "<region>a"]
    --base-name=name    Will be used to name launch config and auto-scaling
                        group.
    --elb-name=name     Name of the elastic load balancer to use
                        [default "elb-<base-name>"]
    --group=group       Name of the AWS security group to use
                        [default: rax-ast-demo-worker]
    --region=region     Name of the AWS regions to use [default: eu-west-1]
HSD
exit 0
}

if [ $# -eq 0 ]; then
    help
fi

action="setup"
azs=""
base_name=""
elb_name="lb-rax-ast-demo"
group="rax-ast-demo-worker"
region="eu-west-1"
ami="ami-3bc7c54f"


# Process the command-line arguments
for i in $*
do
    case $i in
    --action=*)
        action=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --ami=*)
        ami=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --azs=*)
        azs=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --base-name=*)
        base_name=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --elb-name=*)
        elb_name=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --group=*)
        group=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    --region=*)
        region=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
        ;;
    -h|--help)
        help
        ;;
    *)
        echo "!! Uknown option: " $i
        exit 2
        ;;
    esac
done

# Mandatory command-line args
if [ -z "$base_name" ]; then
    echo "!! Please specify a base name."
    exit 3
fi

# Derived parameters
if [ -z "$elb_name" ]; then
    elb_name="elb-$base_name"
fi

if [ -z "$azs" ]; then
    azs="${region}a"
fi


# Do the actual work (setup|teardown)

if [ "$action" == "setup" ]; then
    if [ -z "$group" ]; then
        echo "!! Please specify a security group."
        exit 4
    fi

    as-create-launch-config "lc-$base_name" \
        --group $group \
        --image-id $ami \
        --instance-type m1.small \
        --key aws-ec2 \
        --user-data-file cloud-config.txt \
        --region $region

    as-create-auto-scaling-group "asg-$base_name" \
        --launch-configuration "lc-$base_name" \
        --min-size 1 \
        --max-size 5 \
        --tag "k=name, v=$base_name, p=true" \
        --availability-zones $azs \
        --health-check-type ELB \
        --grace-period 60 \
        --load-balancers $elb_name \
        --region $region

    # Scale up policy
    upp_arn=`as-put-scaling-policy "sp-UP-$base_name" \
        --adjustment 2 \
        --auto-scaling-group "asg-$base_name" \
        --type ChangeInCapacity \
        --cooldown 60 \
        --region $region`

    mon-put-metric-alarm KaseHighCPUAlarm \
        --alarm-actions $upp_arn \
        --metric-name CPUUtilization \
        --namespace "AWS/EC2" \
        --statistic Average \
        --period 60 \
        --evaluation-periods 1 \
        --threshold 59 \
        --comparison-operator GreaterThanOrEqualToThreshold \
        --dimensions "AutoScalingGroupName=asg-$base_name" \
        --region $region

    # Scale down policy
    dnp_arn=`as-put-scaling-policy "sp-DOWN-$base_name" \
        --adjustment=-1 \
        --auto-scaling-group "asg-$base_name" \
        --type ChangeInCapacity \
        --cooldown 60 \
        --region $region`

    mon-put-metric-alarm KaseLowCPUAlarm \
        --alarm-actions $dnp_arn \
        --metric-name CPUUtilization \
        --namespace "AWS/EC2" \
        --statistic Average \
        --period 60 \
        --evaluation-periods 1 \
        --threshold 41 \
        --comparison-operator LessThanOrEqualToThreshold \
        --dimensions "AutoScalingGroupName=asg-$base_name" \
        --region $region
else
    # The teardown case
    as-delete-auto-scaling-group "asg-$base_name" \
        --force \
        --force-delete \
        --region $region
    as-delete-launch-config "lc-$base_name" \
        --force \
        --region $region
    as-delete-policy "sp-UP-$base_name" \
        --force \
        --auto-scaling-group "asg-$base_name" \
        --region $region
    as-delete-policy "sp-DOWN-$base_name" \
        --force \
        --auto-scaling-group "asg-$base_name" \
        --region $region
    mon-delete-alarms KaseHighCPUAlarm KaseLowCPUAlarm --force
fi
